// lib/services/aiPromptsService.ts

// Array of AI-crafted journal prompts organized by categories
const AI_JOURNAL_PROMPTS = {
  reflection: [
    "Using AI insight, reflect on a moment recently that challenged your perspective. How did it change you?",
    "AI suggests exploring: What patterns do you notice in your emotional responses lately?",
    "Through an AI lens: What would your life story look like if told from the perspective of your future self?",
    "AI prompt: Describe a time when you felt truly authentic. What enabled that feeling?",
    "With AI guidance: What beliefs have you inherited that no longer serve you?",
    "AI reflection: What masks do you wear in different situations, and when do you feel most yourself?",
    "AI-generated question: If your inner critic had a voice, what would it say and how would you respond?",
  ],
  growth: [
    "AI analysis suggests: What skill would transform your life if you mastered it in the next year?",
    "AI growth prompt: Describe your comfort zone and one step you could take beyond it this week.",
    "Through AI assessment: What failures have taught you the most valuable lessons?",
    "AI asks: What obstacles do you create for yourself, and how might you dismantle them?",
    "Based on AI patterns: If you could instantly upgrade three aspects of yourself, what would they be?",
    "AI prompt: What knowledge gaps are holding you back from your next level of growth?",
    "AI suggests exploring: What would you attempt if you knew you had the full support of everyone in your life?",
  ],
  relationships: [
    "AI relationship analysis: How do your past relationships influence your current connections?",
    "Generated by AI: What boundaries could you establish that would improve your key relationships?",
    "AI prompt: How do you show up differently with different people, and why?",
    "AI suggests reflecting: What do you need from your closest relationships that you're not receiving?",
    "Through AI assessment: How does your communication style help or hinder your connections?",
    "AI relationship prompt: What unspoken expectations do you have of others?",
    "AI analysis suggests: How would your relationships change if you were completely honest?",
  ],
  wellbeing: [
    "AI wellbeing prompt: What aspects of your self-care routine genuinely nourish you versus what you do out of obligation?",
    "AI generated: Describe your relationship with rest. When do you allow yourself to truly recharge?",
    "AI suggests: What sensations in your body are you ignoring that deserve attention?",
    "Through AI analysis: How does your environment affect your mental state, and what could you modify?",
    "AI wellbeing assessment: What brings you a sense of peace amid chaos?",
    "AI prompt: How do you define healing, and where are you in that process?",
    "AI suggests exploring: What would perfect balance look like in your life right now?",
  ],
  purpose: [
    "AI purpose prompt: What contribution would you like to make that extends beyond your lifetime?",
    "Generated by AI: When do you feel most aligned with your sense of purpose?",
    "AI suggests reflecting: What forms of impact are most meaningful to you?",
    "AI analysis: What talents or gifts do you possess that you haven't fully expressed?",
    "Through AI assessment: What would you regret not pursuing or creating?",
    "AI purpose prompt: How would you define success if external validation wasn't a factor?",
    "AI suggests: What message do you feel compelled to share with the world?",
  ],
  imagination: [
    "AI creativity prompt: If you could design your ideal day with no limitations, what would it include?",
    "Generated by AI: What would you pursue if failure was impossible?",
    "AI suggests imagining: If you could receive advice from anyone in history, who would it be and what would you ask?",
    "AI prompt: If your life were a novel, what would the next chapter contain?",
    "Through AI imagination: What alternative life paths intrigue you most?",
    "AI suggests: If you could solve one global problem, what would it be and how would you approach it?",
    "AI-generated scenario: Imagine waking up tomorrow with one extraordinary ability. What would it be and how would you use it?",
  ],
}

// Function to get a random AI prompt from all categories
export function getRandomAIPrompt(): string {
  // Flatten all prompts into a single array
  const allPrompts = Object.values(AI_JOURNAL_PROMPTS).flat()

  // Get a random index
  const randomIndex = Math.floor(Math.random() * allPrompts.length)

  // Return the random prompt
  return allPrompts[randomIndex]
}

// Function to get a random AI prompt from a specific category
export function getRandomAIPromptFromCategory(
  category: keyof typeof AI_JOURNAL_PROMPTS
): string {
  const categoryPrompts = AI_JOURNAL_PROMPTS[category]
  const randomIndex = Math.floor(Math.random() * categoryPrompts.length)
  return categoryPrompts[randomIndex]
}

// Function to get a different random AI prompt (useful for refresh functionality)
export function getNewRandomAIPrompt(currentPrompt: string): string {
  let newPrompt = getRandomAIPrompt()

  // Make sure we don't get the same prompt twice
  while (
    newPrompt === currentPrompt &&
    Object.values(AI_JOURNAL_PROMPTS).flat().length > 1
  ) {
    newPrompt = getRandomAIPrompt()
  }

  return newPrompt
}

// Get all available AI prompt categories
export function getAIPromptCategories(): string[] {
  return Object.keys(AI_JOURNAL_PROMPTS)
}

// Export all AI prompts for reference
export { AI_JOURNAL_PROMPTS }
